### ISSUE TITLE
Onboarding checklist

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/blueprints#26]
This checklist focuses on the aspects specific to the epiverse-trace project, and relevant to members from all institutions. Each partner institution is expected to provide their own specific onboarding process in addition to the points listed here:

- [ ] Add to the GitHub organisation & the relevant team
  - [ ] Recommend passing org membership to public
  - [ ] Recommend adding themselves as packagetemplate contributor
- [ ] Add to the relevant slack channels
  - [ ] Show running agenda and notes for allRSEs weekly meeting 
- [ ] Forward relevant event series invites
- [ ] Give a quick tour of the existing infrastructure shared by all packages
  - [ ] r-universe
  - [ ] automated PR reviews (R CMD check, lintr)
  - [ ] packagetemplate & how to use it
  - [ ] website

**Comment by Bisaloo** [comment]
Superseded by https://github.com/epiverse-trace/.github/pull/55.
